### ISSUE TITLE
Exception error when running  on 1.18 paper (fork) server

### ISSUE THREAD

**Issue by roxandtol** [Ruinscraft/Powder#20]
Tried the async setting on config.yml, but I still get the same error.
```
17:09:32 ERROR]: Thread Craft Scheduler Thread - 15 - Powder failed main thread check: Chunk getEntities call
java.lang.Throwable: null
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:15) ~[purpur-1.18.2.jar:git-Purpur-1609]
	at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2435) ~[?:?]
	at net.minecraft.server.level.ServerLevel.getEntity(ServerLevel.java:1872) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.getEntity(CraftServer.java:2482) ~[purpur-1.18.2.jar:git-Purpur-1609]
	at org.bukkit.Bukkit.getEntity(Bukkit.java:1983) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at com.ruinscraft.powder.model.tracker.EntityTracker.getEntityLocation(EntityTracker.java:78) ~[Powder-0.2.1(1).jar:?]
	at com.ruinscraft.powder.model.tracker.EntityTracker.refreshLocation(EntityTracker.java:64) ~[Powder-0.2.1(1).jar:?]
	at com.ruinscraft.powder.model.tracker.EntityTracker.<init>(EntityTracker.java:29) ~[Powder-0.2.1(1).jar:?]
	at com.ruinscraft.powder.model.Powder.lambda$1(Powder.java:270) ~[Powder-0.2.1(1).jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1609]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1609]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1609]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:09:32 WARN]: [Powder] Plugin Powder v0.2.1 generated an exception while executing task 496
java.lang.IllegalStateException: Asynchronous Chunk getEntities call!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:16) ~[purpur-1.18.2.jar:git-Purpur-1609]
	at net.minecraft.server.level.ServerLevel.getEntities(ServerLevel.java:2435) ~[?:?]
	at net.minecraft.server.level.ServerLevel.getEntity(ServerLevel.java:1872) ~[?:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.getEntity(CraftServer.java:2482) ~[purpur-1.18.2.jar:git-Purpur-1609]
	at org.bukkit.Bukkit.getEntity(Bukkit.java:1983) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at com.ruinscraft.powder.model.tracker.EntityTracker.getEntityLocation(EntityTracker.java:78) ~[Powder-0.2.1(1).jar:?]
	at com.ruinscraft.powder.model.tracker.EntityTracker.refreshLocation(EntityTracker.java:64) ~[Powder-0.2.1(1).jar:?]
	at com.ruinscraft.powder.model.tracker.EntityTracker.<init>(EntityTracker.java:29) ~[Powder-0.2.1(1).jar:?]
	at com.ruinscraft.powder.model.Powder.lambda$1(Powder.java:270) ~[Powder-0.2.1(1).jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.2.jar:git-Purpur-1609]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.2.jar:git-Purpur-1609]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.2.jar:git-Purpur-1609]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	```

I also tried using a version built from source, but it wouldn't start at all

**Comment by Ilyushya** [comment]
Hello! The plugin is not adapted for 1.18 (yet, I hope).
![изображение](https://user-images.githubusercontent.com/98094811/209528050-4bd51ebb-718e-47af-8fc0-45870603d6db.png)
